
language: csharp
sudo: false # faster builds
solution: ./JwtService.sln
dist: trusty
notifications:
  email: false
install:
  - dotnet restore ./JwtService.sln
mono: none
dotnet: 2.1.300
script:
  - dotnet restore ./JwtService.sln
  - cd tests/
  - dotnet test
  